18.08.2024  fixed Expression Maker.h
 POperand MakeFunctionCall( POperand &fn, const PExpressionList &params
);

Fixed bug:
cmake --build . --target all
[  6%] Built target nrc
[  9%] Building CXX object nrcpp/CMakeFiles/nrcpp.dir/Body.cpp.obj
[ 12%] Building CXX object nrcpp/CMakeFiles/nrcpp.dir/BodyMaker.cpp.obj
[ 15%] Building CXX object
nrcpp/CMakeFiles/nrcpp.dir/Coordinator.cpp.obj
[ 18%] Building CXX object
nrcpp/CMakeFiles/nrcpp.dir/ExpressionChecker.cpp.obj
D:\nrcpp\nrcpp\ExpressionChecker.cpp:170:94: error: 'POperand
ExpressionMakerUtils::MakeFunctionCall(POperand&, const
PExpressionList&)' should have been declared inside
'ExpressionMakerUtils'
  170 | POperand ExpressionMakerUtils::MakeFunctionCall( POperand &fn,
const PExpressionList &params )
      |
^
mingw32-make[2]: *** [nrcpp\CMakeFiles\nrcpp.dir\build.make:166:
nrcpp/CMakeFiles/nrcpp.dir/ExpressionChecker.cpp.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:159:
nrcpp/CMakeFiles/nrcpp.dir/all] Error 2
mingw32-make: *** [Makefile:90: all] Error 2